name: Check

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn
      - name: Lint
        run: yarn test:lint

  type:
    name: Type
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn
      - name: Type
        run: yarn test:type

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
