name: Release

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Release
        # https://github.com/semantic-release/git#environment-variables
        env:
          GIT_AUTHOR_NAME: Ivan Gabriele
          GIT_AUTHOR_EMAIL: ivan.gabriele@gmail.com
          GIT_COMMITTER_NAME: Ivan Gabriele
          GIT_COMMITTER_EMAIL: ivan.gabriele@gmail.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release

  deploy:
    name: Deploy
    needs: release
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build-storybook
      - name: Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d storybook-static -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
